In [23]:
import os
from google.colab import drive
import pandas as pd

# Configura Pandas para mostrar todas las filas y columnas

In [24]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# Montar datos del drive

In [25]:
drive.mount('/content/drive')

folder_path = '/content/drive/MyDrive/BigData IA/ProyectoFinal/DatosParquet/'

if os.path.exists(folder_path):
    print(f"Contents of '{folder_path}':")
    for item in os.listdir(folder_path):
        print(item)
else:
    print(f"The folder '{folder_path}' does not exist. Please check the path and try again.")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Contents of '/content/drive/MyDrive/BigData IA/ProyectoFinal/DatosParquet/':
Alquileres-usuarios-foráneos.parquet
Alquileres.parquet

In [26]:
# Todos los alquileres
Alquileres_df = pd.read_parquet(f'{folder_path}/Alquileres.parquet')
print('Alquileres.parquet:')
display(Alquileres_df.head())

# Solo de otros paises
Alquileres_usuarios_foráneos_df = pd.read_parquet(f'{folder_path}/Alquileres-usuarios-foráneos.parquet')
print('\n Alquileres_usuarios_foráneos.parquet:')
display(Alquileres_usuarios_foráneos_df.head())

Alquileres.parquet:

,Start,End,Minutos,Rental place,Return place
0,2024-04-01 06:00:04,2024-04-01 06:09:36,9.533333,Torre Las Palmas,San Telmo
1,2024-04-01 06:00:46,2024-04-01 06:12:17,11.516667,Base Naval,Intermodal El Rincón
2,2024-04-01 06:10:52,2024-04-01 06:17:03,6.183333,Churruca,Parque Santa Catalina
3,2024-04-01 06:24:54,2024-04-01 06:32:13,7.316667,Torre Las Palmas,Plaza de España
4,2024-04-01 06:28:46,2024-04-01 06:35:03,6.283333,Las Canteras - Luis Morote,Churruca

 Alquileres_usuarios_foráneos.parquet:

,Start time,End time,Rental place,Return place,PAÍS
0,2024-04-01 07:21:08,2024-04-01 07:50:11,Las Canteras - Luis Morote,San Cristóbal,Austria
1,2024-04-01 08:43:50,2024-04-01 08:55:16,Castillo de Mata (elect.),Plaza de España (elect.),Italia
2,2024-04-01 09:54:27,2024-04-01 10:06:59,Las Canteras - Luis Morote,Intermodal El Rincón,Alemania
3,2024-04-01 09:54:47,2024-04-01 10:06:39,Las Canteras - Luis Morote,Intermodal El Rincón,Alemania
4,2024-04-01 10:24:49,2024-04-01 10:30:30,Torre Woermann,Las Canteras - Luis Morote,Alemania

# Formalizacion del dataset

In [27]:
Alquileres_usuarios_foráneos_df = Alquileres_usuarios_foráneos_df.rename(columns={'Start time': 'Start', 'End time': 'End'})
print('Columnas renombradas en Alquileres_usuarios_foráneos_df:')
display(Alquileres_usuarios_foráneos_df.head())

Columnas renombradas en Alquileres_usuarios_foráneos_df:

,Start,End,Rental place,Return place,PAÍS
0,2024-04-01 07:21:08,2024-04-01 07:50:11,Las Canteras - Luis Morote,San Cristóbal,Austria
1,2024-04-01 08:43:50,2024-04-01 08:55:16,Castillo de Mata (elect.),Plaza de España (elect.),Italia
2,2024-04-01 09:54:27,2024-04-01 10:06:59,Las Canteras - Luis Morote,Intermodal El Rincón,Alemania
3,2024-04-01 09:54:47,2024-04-01 10:06:39,Las Canteras - Luis Morote,Intermodal El Rincón,Alemania
4,2024-04-01 10:24:49,2024-04-01 10:30:30,Torre Woermann,Las Canteras - Luis Morote,Alemania

# Preparacion del dataset

In [28]:
import pandas as pd

# Seleccionar solo las columnas 'Start', 'End' y 'PAÍS' de Alquileres_usuarios_foráneos_df
foreign_users_country_df = Alquileres_usuarios_foráneos_df[['Start', 'End', 'PAÍS']]

# Realizar un left merge para añadir solo la columna 'PAÍS' a Alquileres_df
alquileres_merged_df = pd.merge(Alquileres_df, foreign_users_country_df, on=['Start', 'End'], how='left')

print('Alquileres y la columna PAÍS de Alquileres_usuarios_foráneos unidos por Start y End (left merge):')
display(alquileres_merged_df.head())

Alquileres y la columna PAÍS de Alquileres_usuarios_foráneos unidos por Start y End (left merge):

,Start,End,Minutos,Rental place,Return place,PAÍS
0,2024-04-01 06:00:04,2024-04-01 06:09:36,9.533333,Torre Las Palmas,San Telmo,NaN
1,2024-04-01 06:00:46,2024-04-01 06:12:17,11.516667,Base Naval,Intermodal El Rincón,NaN
2,2024-04-01 06:10:52,2024-04-01 06:17:03,6.183333,Churruca,Parque Santa Catalina,NaN
3,2024-04-01 06:24:54,2024-04-01 06:32:13,7.316667,Torre Las Palmas,Plaza de España,NaN
4,2024-04-01 06:28:46,2024-04-01 06:35:03,6.283333,Las Canteras - Luis Morote,Churruca,NaN

## Sustituir NAN por España

In [29]:
alquileres_merged_df['PAÍS'] = alquileres_merged_df['PAÍS'].fillna('España')
print('NaNs en la columna PAÍS reemplazados por España:')
display(alquileres_merged_df.head())

NaNs en la columna PAÍS reemplazados por España:

,Start,End,Minutos,Rental place,Return place,PAÍS
0,2024-04-01 06:00:04,2024-04-01 06:09:36,9.533333,Torre Las Palmas,San Telmo,España
1,2024-04-01 06:00:46,2024-04-01 06:12:17,11.516667,Base Naval,Intermodal El Rincón,España
2,2024-04-01 06:10:52,2024-04-01 06:17:03,6.183333,Churruca,Parque Santa Catalina,España
3,2024-04-01 06:24:54,2024-04-01 06:32:13,7.316667,Torre Las Palmas,Plaza de España,España
4,2024-04-01 06:28:46,2024-04-01 06:35:03,6.283333,Las Canteras - Luis Morote,Churruca,España

## Separar la hora de la fecha

In [30]:
alquileres_merged_df['Start'] = pd.to_datetime(alquileres_merged_df['Start'])
alquileres_merged_df['Date'] = alquileres_merged_df['Start'].dt.date
alquileres_merged_df['Start'] = alquileres_merged_df['Start'].dt.time

print('Columna Start separada en Date y Start (hora):')
display(alquileres_merged_df.head())

Columna Start separada en Date y Start (hora):

,Start,End,Minutos,Rental place,Return place,PAÍS,Date
0,06:00:04,2024-04-01 06:09:36,9.533333,Torre Las Palmas,San Telmo,España,2024-04-01
1,06:00:46,2024-04-01 06:12:17,11.516667,Base Naval,Intermodal El Rincón,España,2024-04-01
2,06:10:52,2024-04-01 06:17:03,6.183333,Churruca,Parque Santa Catalina,España,2024-04-01
3,06:24:54,2024-04-01 06:32:13,7.316667,Torre Las Palmas,Plaza de España,España,2024-04-01
4,06:28:46,2024-04-01 06:35:03,6.283333,Las Canteras - Luis Morote,Churruca,España,2024-04-01

## Borrar end ya que tenemos cuanto duro el trayecto

In [31]:
alquileres_merged_df = alquileres_merged_df.drop('End', axis=1)

print('Columna End eliminada:')
display(alquileres_merged_df.head())

Columna End eliminada:

,Start,Minutos,Rental place,Return place,PAÍS,Date
0,06:00:04,9.533333,Torre Las Palmas,San Telmo,España,2024-04-01
1,06:00:46,11.516667,Base Naval,Intermodal El Rincón,España,2024-04-01
2,06:10:52,6.183333,Churruca,Parque Santa Catalina,España,2024-04-01
3,06:24:54,7.316667,Torre Las Palmas,Plaza de España,España,2024-04-01
4,06:28:46,6.283333,Las Canteras - Luis Morote,Churruca,España,2024-04-01

## Quedarnos solo con las farnjas horarias

In [32]:
alquileres_merged_df['Start'] = alquileres_merged_df['Start'].apply(lambda x: x.strftime('%H')).astype(int)

print('Columna Start transformada para mostrar solo la hora como entero:')
display(alquileres_merged_df.head())

Columna Start transformada para mostrar solo la hora como entero:

,Start,Minutos,Rental place,Return place,PAÍS,Date
0,6,9.533333,Torre Las Palmas,San Telmo,España,2024-04-01
1,6,11.516667,Base Naval,Intermodal El Rincón,España,2024-04-01
2,6,6.183333,Churruca,Parque Santa Catalina,España,2024-04-01
3,6,7.316667,Torre Las Palmas,Plaza de España,España,2024-04-01
4,6,6.283333,Las Canteras - Luis Morote,Churruca,España,2024-04-01

## Separar Date en Dia y mes

In [33]:
alquileres_merged_df['Date'] = pd.to_datetime(alquileres_merged_df['Date'])
alquileres_merged_df['Day'] = alquileres_merged_df['Date'].dt.day
alquileres_merged_df['Month'] = alquileres_merged_df['Date'].dt.month
alquileres_merged_df = alquileres_merged_df.drop('Date', axis=1)

print('Columna Date separada en Day y Month:')
display(alquileres_merged_df.head())

Columna Date separada en Day y Month:

,Start,Minutos,Rental place,Return place,PAÍS,Day,Month
0,6,9.533333,Torre Las Palmas,San Telmo,España,1,4
1,6,11.516667,Base Naval,Intermodal El Rincón,España,1,4
2,6,6.183333,Churruca,Parque Santa Catalina,España,1,4
3,6,7.316667,Torre Las Palmas,Plaza de España,España,1,4
4,6,6.283333,Las Canteras - Luis Morote,Churruca,España,1,4

Guardar categoricos

In [34]:
alquileres_merged_df_con_categoricas = alquileres_merged_df.copy()

## Asignar un numero a cada estacion

### Creo un mapeo global para todas las estaciones

In [35]:
all_unique_places = pd.concat([
    alquileres_merged_df['Rental place'],
    alquileres_merged_df['Return place']
]).unique()

# Crea los ID
place_to_id, _ = pd.factorize(all_unique_places)

# Crea un diccionario con (lugar,ID)
place_mapping = dict(zip(all_unique_places, place_to_id))

### Aplicando el mapeo

In [36]:
alquileres_merged_df['RentalPlace'] = alquileres_merged_df['Rental place'].map(place_mapping)
alquileres_merged_df['ReturnPlace'] = alquileres_merged_df['Return place'].map(place_mapping)

print('DataFrame con IDs globales para Rental place y Return place:')
display(alquileres_merged_df.head())

DataFrame con IDs globales para Rental place y Return place:

,Start,Minutos,Rental place,Return place,PAÍS,Day,Month,RentalPlace,ReturnPlace
0,6,9.533333,Torre Las Palmas,San Telmo,España,1,4,0,20
1,6,11.516667,Base Naval,Intermodal El Rincón,España,1,4,1,35
2,6,6.183333,Churruca,Parque Santa Catalina,España,1,4,2,8
3,6,7.316667,Torre Las Palmas,Plaza de España,España,1,4,0,13
4,6,6.283333,Las Canteras - Luis Morote,Churruca,España,1,4,3,2

### Eliminamos las columnas con los valores antiguos

In [37]:
alquileres_merged_df = alquileres_merged_df.drop(columns=['Rental place', 'Return place'])

print('Columnas Rental place y Return place eliminadas:')
display(alquileres_merged_df.head())

Columnas Rental place y Return place eliminadas:

   Start    Minutos    PAÍS  Day  Month  RentalPlace  ReturnPlace
0      6   9.533333  España    1      4            0           20
1      6  11.516667  España    1      4            1           35
2      6   6.183333  España    1      4            2            8
3      6   7.316667  España    1      4            0           13
4      6   6.283333  España    1      4            3            2

## Asignar numero a los paises

In [38]:
codes, unique_country_labels = pd.factorize(alquileres_merged_df['PAÍS'])

country_mapping = dict(zip(unique_country_labels, range(len(unique_country_labels))))

alquileres_merged_df['Country'] = alquileres_merged_df['PAÍS'].map(country_mapping)

print('Columna PAÍS con IDs numéricos:')
display(alquileres_merged_df.head())

Columna PAÍS con IDs numéricos:

   Start    Minutos    PAÍS  Day  Month  RentalPlace  ReturnPlace  Country
0      6   9.533333  España    1      4            0           20        0
1      6  11.516667  España    1      4            1           35        0
2      6   6.183333  España    1      4            2            8        0
3      6   7.316667  España    1      4            0           13        0
4      6   6.283333  España    1      4            3            2        0

### Eliminamos Columna Pais

In [39]:
alquileres_merged_df = alquileres_merged_df.drop('PAÍS', axis=1)

print('Columna PAÍS eliminada:')
display(alquileres_merged_df.head())

Columna PAÍS eliminada:

   Start    Minutos  Day  Month  RentalPlace  ReturnPlace  Country
0      6   9.533333    1      4            0           20        0
1      6  11.516667    1      4            1           35        0
2      6   6.183333    1      4            2            8        0
3      6   7.316667    1      4            0           13        0
4      6   6.283333    1      4            3            2        0

## Cambiar el nombre a la columna minutos

In [40]:
alquileres_merged_df = alquileres_merged_df.rename(columns={'Minutos': 'Time'})
alquileres_merged_df_con_categoricas = alquileres_merged_df_con_categoricas.rename(columns={'Minutos': 'Time'})

print('Columna Minutos renombrada a Time:')
display(alquileres_merged_df.head())

Columna Minutos renombrada a Time:

   Start       Time  Day  Month  RentalPlace  ReturnPlace  Country
0      6   9.533333    1      4            0           20        0
1      6  11.516667    1      4            1           35        0
2      6   6.183333    1      4            2            8        0
3      6   7.316667    1      4            0           13        0
4      6   6.283333    1      4            3            2        0

# Separamos el data en 4 mas pequeños dependiendo del tiempo

In [41]:
alquileres_merged_df_30_min = alquileres_merged_df[alquileres_merged_df['Time'] < 30]
alquileres_merged_df_30_min_categoricas = alquileres_merged_df_con_categoricas[alquileres_merged_df_con_categoricas['Time'] < 30]

alquileres_merged_df_3_horas = alquileres_merged_df[(alquileres_merged_df['Time'] >= 30) & (alquileres_merged_df['Time'] < 180)]
alquileres_merged_df_3_horas_categoricas = alquileres_merged_df_con_categoricas[(alquileres_merged_df_con_categoricas['Time'] >= 30) & (alquileres_merged_df_con_categoricas['Time'] < 180)]

alquileres_merged_df_dia_completo = alquileres_merged_df[alquileres_merged_df['Time'] >= 180]
alquileres_merged_df_mas_3_horas_categoricas = alquileres_merged_df_con_categoricas[alquileres_merged_df_con_categoricas['Time'] >= 180]

print(f"Número de elementos en 'alquileres_merged_df_30_min': {alquileres_merged_df_30_min.shape[0]}")
print(f"Número de elementos en 'alquileres_merged_df_30_min_categoricas': {alquileres_merged_df_30_min_categoricas.shape[0]}")

print(f"Número de elementos en 'alquileres_merged_df_3_horas': {alquileres_merged_df_3_horas.shape[0]}")
print(f"Número de elementos en 'alquileres_merged_df_3_horas_categoricas': {alquileres_merged_df_3_horas_categoricas.shape[0]}")

print(f"Número de elementos en 'alquileres_merged_df_dia_completo': {alquileres_merged_df_dia_completo.shape[0]}")
print(f"Número de elementos en 'alquileres_merged_df_mas_3_horas_categoricas': {alquileres_merged_df_mas_3_horas_categoricas.shape[0]}")

Número de elementos en 'alquileres_merged_df_30_min': 568819
Número de elementos en 'alquileres_merged_df_30_min_categoricas': 568819
Número de elementos en 'alquileres_merged_df_3_horas': 51192
Número de elementos en 'alquileres_merged_df_3_horas_categoricas': 51192
Número de elementos en 'alquileres_merged_df_dia_completo': 1886
Número de elementos en 'alquileres_merged_df_mas_3_horas_categoricas': 1886

# Modelos predictivo

## Buscando mejores hiperparametros con random search para xgboost

In [42]:
import time
import xgboost as xgb
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from scipy.stats import uniform
import time
import psutil
import os

if(False):

  # Mediciones
  process = psutil.Process(os.getpid())
  inicio_tiempo = time.time()
  inicio_ram = process.memory_info().rss / 1024**2

  # Define features (X) and target (y)
  X = alquileres_merged_df_30_min.drop('Time', axis=1)
  y = alquileres_merged_df_30_min['Time']

  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Define the parameter distribution for RandomizedSearchCV
  param_dist = {
      'n_estimators': [100, 200, 300, 500, 700, 1000],
      'learning_rate': uniform(0.01, 0.2),
      'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
      'subsample': uniform(0.6, 0.4),
      'colsample_bytree': uniform(0.6, 0.4)
  }

  # Initialize XGBoost Regressor model
  xgb_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)

  # Initialize RandomizedSearchCV
  random_search = RandomizedSearchCV(estimator=xgb_model,
                                      param_distributions=param_dist,
                                      n_iter=50,  # Number of parameter settings that are sampled
                                      scoring='neg_mean_squared_error',
                                      cv=3,  # 3-fold cross-validation
                                      verbose=1,
                                      random_state=42,
                                      n_jobs=-1) # Use all available cores

  # Fit RandomizedSearchCV to the training data
  random_search.fit(X_train, y_train)

  # Print the best hyperparameters
  mejoresHiperparametrosXgboost = random_search.best_params_
  print(f'Mejores hiperparámetros encontrados: {random_search.best_params_}')

  # Get the best model
  modelo30Min = random_search.best_estimator_

  # Make predictions on the test set
  y_pred = modelo30Min.predict(X_test)

  # Evaluate the model
  mse = mean_squared_error(y_test, y_pred)
  mae = mean_absolute_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)
  print(f'Mean Squared Error (con Random Search): {mse:.2f}')
  print(f'Mean Absolute Error (con Random Search): {mae:.2f}')
  print(f'R-squared (con Random Search): {r2:.2f}')

  fin_tiempo = time.time()
  fin_ram = process.memory_info().rss / 1024**2
  cpu = psutil.cpu_percent(interval=1)

  print("Tiempo de ejecución:", fin_tiempo - inicio_tiempo, "segundos")
  print("RAM inicio:", inicio_ram, "MB")
  print("RAM final:", fin_ram, "MB")
  print("CPU uso:", cpu, "%")

## Buscando mejores hiperparametros con random search para catboost

In [ ]:
import time
# import xgboost as xgb # Removed as CatBoost is used
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from scipy.stats import uniform
import time
import psutil
import os
from catboost import CatBoostRegressor # Import CatBoost

if(True): # Changed to True to enable execution

  # Mediciones
  process = psutil.Process(os.getpid())
  inicio_tiempo = time.time()
  inicio_ram = process.memory_info().rss / 1024**2

  # Define features (X) and target (y) using the specified dataframe
  X = alquileres_merged_df_30_min_categoricas.drop('Time', axis=1)
  y = alquileres_merged_df_30_min_categoricas['Time']

  # Identify categorical features for CatBoost
  categorical_features_indices = X.select_dtypes(include=['object']).columns.tolist()

  # Split data into training and testing sets
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

  # Define the parameter distribution for RandomizedSearchCV for CatBoost
  param_dist = {
      'iterations': [100, 200, 300, 500, 700, 1000], # Equivalent to n_estimators
      'learning_rate': uniform(0.01, 0.2),
      'depth': [3, 4, 5, 6, 7, 8, 9, 10], # Equivalent to max_depth
      'l2_leaf_reg': uniform(1, 10), # L2 regularization
      'border_count': [32, 64, 128, 254], # For numerical features quantization
      'min_data_in_leaf': [1, 5, 10, 20] # For preventing overfitting
  }

  # Initialize CatBoost Regressor model WITHOUT cat_features in constructor
  cat_model = CatBoostRegressor(objective='RMSE', # CatBoost uses RMSE for regression objective
                               random_seed=42,
                               verbose=False) # Set to True for verbose output during training

  # Initialize RandomizedSearchCV
  random_search = RandomizedSearchCV(estimator=cat_model,
                                      param_distributions=param_dist,
                                      n_iter=50,  # Number of parameter settings that are sampled
                                      scoring='neg_mean_squared_error', # Keep scoring for consistency
                                      cv=3,  # 3-fold cross-validation
                                      verbose=1,
                                      random_state=42,
                                      n_jobs=-1) # Use all available cores

  # Fit RandomizedSearchCV to the training data, passing cat_features here
  random_search.fit(X_train, y_train, cat_features=categorical_features_indices)

  # Print the best hyperparameters
  mejoresHiperparametrosCatboost = random_search.best_params_ # Storing in a new variable
  print(f'Mejores hiperparámetros encontrados (CatBoost): {random_search.best_params_}')

  # Get the best model
  modelo30MinCatboost = random_search.best_estimator_ # Storing in a new variable

  # Make predictions on the test set
  y_pred = modelo30MinCatboost.predict(X_test)

  # Evaluate the model
  mse = mean_squared_error(y_test, y_pred)
  mae = mean_absolute_error(y_test, y_pred)
  r2 = r2_score(y_test, y_pred)
  print(f'Mean Squared Error (con Random Search, CatBoost): {mse:.2f}')
  print(f'Mean Absolute Error (con Random Search, CatBoost): {mae:.2f}')
  print(f'R-squared (con Random Search, CatBoost): {r2:.2f}')

  fin_tiempo = time.time()
  fin_ram = process.memory_info().rss / 1024**2
  cpu = psutil.cpu_percent(interval=1)

  print("Tiempo de ejecución:", fin_tiempo - inicio_tiempo, "segundos")
  print("RAM inicio:", inicio_ram, "MB")
  print("RAM final:", fin_ram, "MB")
  print("CPU uso:", cpu, "%")

Fitting 3 folds for each of 50 candidates, totalling 150 fits

## Modelo para 30 min

### Xgboost hiperparametros genericos

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_30_min.drop('Time', axis=1)
y = alquileres_merged_df_30_min['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
# Changed learning_rate from 0. to 0.1 to allow the model to learn
modelo30Min = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=300, learning_rate=0.1, random_state=42)

# Train the model
modelo30Min.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo30Min.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'-------------------30 MINUTOS(xgboost)-------------------')
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Xgboost mejores hiperparametros del random search

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_30_min.drop('Time', axis=1)
y = alquileres_merged_df_30_min['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
# Changed learning_rate from 0. to 0.1 to allow the model to learn
modelo30Min = xgb.XGBRegressor(objective='reg:squarederror',random_state=42 ,colsample_bytree=0.873 ,learning_rate=0.098 ,max_depth=9 ,n_estimators=500 ,subsample=0.798)

# Train the model
modelo30Min.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo30Min.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'-------------------30 MINUTOS(xgboost)-------------------')
print(f'Mean Squared Error(xgboost): {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Ejemplo de prediccion Xgboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record, ensuring all original features are present
# Use X_test.columns to ensure consistent feature names and order with the trained model
random_sample_record = X_test.loc[[random_index], X_train.columns]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction using
predicted_time = modelo30Min.predict(random_sample_record)

print(f'-------------------30 MINUTOS(xgboost)-------------------')
print(f"Registro de ejemplo aleatorio:\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")

### CatBoost hiperparametros genericos

In [ ]:
import catboost as cb # Import CatBoost
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_30_min_categoricas.drop('Time', axis=1)
y = alquileres_merged_df_30_min_categoricas['Time']

# Identify categorical features
categorical_features_indices = X.select_dtypes(include=['object']).columns.tolist()

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize CatBoost Regressor model
# Pass categorical_features_indices to the CatBoost model
# Using some common hyperparameters, you can further optimize these if needed
modelo30MinCategoricas = cb.CatBoostRegressor(
    iterations=500,  # Number of boosting rounds
    learning_rate=0.1,
    depth=7,
    loss_function='RMSE',
    random_seed=42,
    verbose=False, # Set to True for verbose output
    cat_features=categorical_features_indices # Specify categorical features
)

# Train the model
modelo30MinCategoricas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo30MinCategoricas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------30 MINUTOS(catboost)------------------')
print(f'Mean Squared Error (CatBoost): {mse:.2f}')
print(f'Mean Absolute Error (CatBoost): {mae:.2f}')
print(f'R-squared (CatBoost): {r2:.2f}')

### Ejemplo de prediccion Catboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record, ensuring all original features are present
# Use X_test.columns to ensure consistent feature names and order with the trained model
random_sample_record = X_test.loc[[random_index], X_train.columns]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction
predicted_time = modelo30MinCategoricas.predict(random_sample_record)

print(f'-------------------30 MINUTOS(catboost)-------------------')
print(f"Registro de ejemplo aleatorio:\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")

## Modelo 3 horas

### Xgboost hiperparametros genericos

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_3_horas.drop(['Time', 'Country'], axis=1)
y = alquileres_merged_df_3_horas['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
modelo3Horas = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=300, learning_rate=0.1, random_state=42)

# Train the model
modelo3Horas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo3Horas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------3 HORAS(xgboost)------------------')
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Xgboost Mejores hiperparametros del random search

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_3_horas.drop(['Time', 'Country'], axis=1)
y = alquileres_merged_df_3_horas['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
modelo3Horas = xgb.XGBRegressor(objective='reg:squarederror',random_state=42 ,colsample_bytree=0.873 ,learning_rate=0.098 ,max_depth=9 ,n_estimators=500 ,subsample=0.798)

# Train the model
modelo3Horas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo3Horas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------3 HORAS(xgboost)------------------')
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Ejemplo de prediccion Xgboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record
random_sample_record = X_test.loc[[random_index]]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction using the modeloForaneo
predicted_time = modelo3Horas.predict(random_sample_record)

print(f'----------------3 HORAS(xgboost)------------------')
print(f"Registro de ejemplo aleatorio (features):\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")

### CatBoost hiperparametros genericos

In [ ]:
# Define features (X) and target (y)
X = alquileres_merged_df_3_horas_categoricas.drop('Time', axis=1)
y = alquileres_merged_df_3_horas_categoricas['Time']

# Identify categorical features
categorical_features_indices = X.select_dtypes(include=['object']).columns.tolist()

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize CatBoost Regressor model
# Pass categorical_features_indices to the CatBoost model
# Using some common hyperparameters, you can further optimize these if needed
modelo3HorasCategoricas = cb.CatBoostRegressor(
    iterations=500,  # Number of boosting rounds
    learning_rate=0.1,
    depth=7,
    loss_function='RMSE',
    random_seed=42,
    verbose=False, # Set to True for verbose output
    cat_features=categorical_features_indices # Specify categorical features
)

# Train the model
modelo3HorasCategoricas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modelo3HorasCategoricas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------3 HORAS(catboost)------------------')
print(f'Mean Squared Error (CatBoost): {mse:.2f}')
print(f'Mean Absolute Error (CatBoost): {mae:.2f}')
print(f'R-squared (CatBoost): {r2:.2f}')

### Ejemplo de prediccion Catboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record, ensuring all original features are present
# Use X_test.columns to ensure consistent feature names and order with the trained model
random_sample_record = X_test.loc[[random_index], X_train.columns]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction
predicted_time = modelo3HorasCategoricas.predict(random_sample_record)

print(f'-------------------3 HORAS(catboost)-------------------')
print(f"Registro de ejemplo aleatorio:\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")

## Modelo mas de 3 horas

### Xgboost hiperparametros genericos

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_mas_3_horas.drop(['Time', 'Country'], axis=1)
y = alquileres_merged_df_mas_3_horas['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
modeloMas3Horas = xgb.XGBRegressor(objective='reg:squarederror', n_estimators=300, learning_rate=0.1, random_state=42)

# Train the model
modeloMas3Horas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modeloMas3Horas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------MAS DE 3 HORAS(xgboost)------------------')
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Xgboost mejores hiperparametros del random search

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Define features (X) and target (y)
X = alquileres_merged_df_mas_3_horas.drop(['Time', 'Country'], axis=1)
y = alquileres_merged_df_mas_3_horas['Time']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize XGBoost Regressor model
modeloMas3Horas = xgb.XGBRegressor(objective='reg:squarederror',random_state=42 ,colsample_bytree=0.873 ,learning_rate=0.098 ,max_depth=9 ,n_estimators=500 ,subsample=0.798)

# Train the model
modeloMas3Horas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modeloMas3Horas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------MAS DE 3 HORAS(xgboost)------------------')
print(f'Mean Squared Error: {mse:.2f}')
print(f'Mean Absolute Error: {mae:.2f}')
print(f'R-squared: {r2:.2f}')

### Ejemplo de prediccion Xgboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record
random_sample_record = X_test.loc[[random_index]]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction using the modeloForaneo
predicted_time = modeloMas3Horas.predict(random_sample_record)

print(f'----------------MAS DE 3 HORAS(xgboost)------------------')
print(f"Registro de ejemplo aleatorio (features):\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")

### CatBoost hiperparametros genericos

In [ ]:
# Define features (X) and target (y)
X = alquileres_merged_df_mas_3_horas_categoricas.drop('Time', axis=1)
y = alquileres_merged_df_mas_3_horas_categoricas['Time']

# Identify categorical features
categorical_features_indices = X.select_dtypes(include=['object']).columns.tolist()

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize CatBoost Regressor model
# Pass categorical_features_indices to the CatBoost model
# Using some common hyperparameters, you can further optimize these if needed
modeloMas3HorasCategoricas = cb.CatBoostRegressor(
    iterations=500,  # Number of boosting rounds
    learning_rate=0.1,
    depth=7,
    loss_function='RMSE',
    random_seed=42,
    verbose=False, # Set to True for verbose output
    cat_features=categorical_features_indices # Specify categorical features
)

# Train the model
modeloMas3HorasCategoricas.fit(X_train, y_train)

# Make predictions on the test set
y_pred = modeloMas3HorasCategoricas.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'----------------MAS DE 3 HORAS(catboost)------------------')
print(f'Mean Squared Error (CatBoost): {mse:.2f}')
print(f'Mean Absolute Error (CatBoost): {mae:.2f}')
print(f'R-squared (CatBoost): {r2:.2f}')

### Ejemplo de prediccion Catboost

In [ ]:
import numpy as np

# Select a random index from the test set
random_index = np.random.choice(X_test.index)

# Get the features for this random record, ensuring all original features are present
# Use X_test.columns to ensure consistent feature names and order with the trained model
random_sample_record = X_test.loc[[random_index], X_train.columns]

# Get the actual 'Time' for this record
actual_time = y_test.loc[random_index]

# Make a prediction
predicted_time = modeloMas3HorasCategoricas.predict(random_sample_record)

print(f'-------------------MAS DE 3 HORAS(catboost)-------------------')
print(f"Registro de ejemplo aleatorio:\n{random_sample_record}")
print(f"Tiempo real (Minutos) para este registro: {actual_time:.2f}")
print(f"Predicción del modelo (Minutos): {predicted_time[0]:.2f}")